### ISSUE TITLE
Подключить postgres к сервису searcher

### ISSUE THREAD

**Issue by timk01** [Java-Java-Bootcamp/FlightSeracher-2022-08#47]
1. Добавить maven пакеты
2. Настроить подлкючение в параметрам сервиса (application.yml)
3. Создать БД flightseacher, пользователь postres, пароль postres
4. Проверить что все работает на тестовой БД (создать тестовую таблицу)

```yaml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flightseacher
    username: postres
    password: postres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        show-sql: true
    hibernate:
      ddl-auto: none
```
